### ISSUE TITLE
[Bug] npm run build - does not work

### ISSUE THREAD

**Issue by einazare** [creativetimofficial/ct-nextjs-argon-dashboard-pro#1]
### Version
1.0.0
### Reproduction link
https://creative-tim.com/product/nextjs-argon-dashboard-pro
### Operating System
Does not matter
### Device
Does not matter
### Browser & Version
Does not matter
### Steps to reproduce
1. Download a fresh copy of NextJS Argon Dashboard PRO
2. Run `npm install` and wait for the installation to complete
3. Run `npm run build` and see that it will fail with an error something like `window is not defined`
### What is expected?
It is expected that the build command would work so that the build output could be delivered on a server.
### What is actually happening?
Build command fails with an error something like `window is not defined`.

---
### Solution
1. Inside the `pages/admin/components.js` we added ad the beginning of the file, the following code:
```
if (typeof window === "undefined") {
  global.window = {};
}
if (typeof document === "undefined") {
  global.document = {};
}
```
2. Inside the `pages/admin/sortable.js` we added ad the beginning of the file, the following code:
```
if (typeof window === "undefined") {
  global.window = {};
}
if (typeof document === "undefined") {
  global.document = {};
}
```
3. Inside the `pages/admin/components.js` we replaced the following code:
```
// react plugin that creates text editor
import ReactQuill from "react-quill";
// javascript plugin that creates nice dropzones for files
import Dropzone from "dropzone";
```
With
```
import dynamic from "next/dynamic";
// react plugin that creates text editor
const ReactQuill = dynamic(() => import("react-quill"));
// javascript plugin that creates nice dropzones for files
const Dropzone = dynamic(() => import("dropzone"));
```
4. Inside the `pages/admin/sortable.js` we replaced the following code:
```
// javascript plugin that creates a sortable object from a dom object
import List from "list.js";
```
With
```
import dynamic from "next/dynamic";
// javascript plugin that creates a sortable object from a dom object
const List = dynamic(() => import("list.js"));
```
### Additional comments
Happy Hacking!

**Comment by tupizz** [comment]
same problem here, I've acquired the product today.

**Comment by einazare** [comment]
Hello there, @tupizz ,

Please check the above solution, it will work.

Best,
Manu

**Comment by austinbiggs** [comment]
This fix worked for me, but I was also experiencing this issue. This fix should be merged into the project.

**Comment by brijzenda** [comment]
Hello @EINazare 

Thanks for helping us out here. We just bought Pro version and immediately ran into this issue. After following steps outlined above I ran into additional issues. Would appreciate your quick response - 

![image](https://user-images.githubusercontent.com/70869444/105614834-e7239d00-5d80-11eb-9aed-7383b8f5b1c3.png)

Thanks
Brij

**Comment by tejasadvait** [comment]
Hey @EINazare,

Thank you for the detailed solution to the 'window not defined' issue. I ran into that issue as soon as I tried building the pro version of the Argon Dashboard. As soon as I follow the steps to solve the 'window not defined' issue, I run into another problem. I get the following error:

> nextjs-argon-dashboard-pro@1.0.0 build /Users/trex/Git/Zenda/AdminPortal/admin_portal_app
> next build

info  - Creating an optimized production build...
Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled

info  - Compiled successfully
info  - Collecting page data...
info  - Generating static pages (0/28)

Error occurred prerendering page "/rtl/rtl-support". Read more: https://err.sh/next.js/prerender-error
ReferenceError: document is not defined
    at new RTL_RTL (/Users/trex/Git/Zenda/AdminPortal/admin_portal_app/.next/server/pages/rtl/rtl-support.js:354:5)
    at d (/Users/trex/Git/Zenda/AdminPortal/admin_portal_app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:320)
    at $a (/Users/trex/Git/Zenda/AdminPortal/admin_portal_app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (/Users/trex/Git/Zenda/AdminPortal/admin_portal_app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (/Users/trex/Git/Zenda/AdminPortal/admin_portal_app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/Users/trex/Git/Zenda/AdminPortal/admin_portal_app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at Object.renderPage (/Users/trex/Git/Zenda/AdminPortal/admin_portal_app/node_modules/next/dist/next-server/server/render.js:54:851)
    at Function.getInitialProps (/Users/trex/Git/Zenda/AdminPortal/admin_portal_app/.next/server/pages/_document.js:327:19)
    at loadGetInitialProps (/Users/trex/Git/Zenda/AdminPortal/admin_portal_app/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/Users/trex/Git/Zenda/AdminPortal/admin_portal_app/node_modules/next/dist/next-server/server/render.js:54:1142)
info  - Generating static pages (7/28)
info  - Generating static pages (14/28)
info  - Generating static pages (21/28)
info  - Generating static pages (28/28)

> Build error occurred
Error: Export encountered errors on following paths:
	/rtl/rtl-support
    at exportApp (/Users/trex/Git/Zenda/AdminPortal/admin_portal_app/node_modules/next/dist/export/index.js:30:1103)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/trex/Git/Zenda/AdminPortal/admin_portal_app/node_modules/next/dist/build/index.js:39:69
    at async /Users/trex/Git/Zenda/AdminPortal/admin_portal_app/node_modules/next/dist/build/tracer.js:1:525
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nextjs-argon-dashboard-pro@1.0.0 build: `next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nextjs-argon-dashboard-pro@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/trex/.npm/_logs/2021-01-23T21_46_37_359Z-debug.log


Any help will be greatly appreciated. Thank you!

Tejas

**Comment by einazare** [comment]
Hello there, @brijzenda @tejasadvait , guys,

Can you please tell me if you've changed anything in our package.json? Did you change the versions that the product comes?

Best,
Manu

**Comment by brijzenda** [comment]
Thanks Manu. We are using the version which came with the distribution. I am pasting below. Is it incompatible with the serverless deployment framework?


----------
{
  "name": "nextjs-argon-dashboard-pro",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "start": "next start",
    "build": "next build",
    "install:clean": "rm -rf -f node_modules/ && rm -rf -f package-lock.json && rm -rf -f .next/ && npm install && npm run dev",
    "compile-sass": "node-sass assets/scss/nextjs-argon-dashboard-pro.scss assets/css/nextjs-argon-dashboard-pro.css",
    "minify-sass": "node-sass assets/scss/nextjs-argon-dashboard-pro.scss assets/css/nextjs-argon-dashboard-pro.min.css --output-style compressed",
    "map-sass": "node-sass assets/scss/nextjs-argon-dashboard-pro.scss assets/css/nextjs-argon-dashboard-pro.css --source-map true",
    "all-sass": "npm run compile-sass && npm run minify-sass && npm run map-sass",
    "dev": "next dev"
  },
  "dependencies": {
    "@fullcalendar/core": "5.3.0",
    "@fullcalendar/daygrid": "5.3.0",
    "@fullcalendar/interaction": "5.3.0",
    "@sls-next/serverless-component": "^1.18.0",
    "@zeit/next-css": "1.0.1",
    "@zeit/next-sass": "1.0.1",
    "chart.js": "2.9.3",
    "classnames": "2.2.6",
    "dropzone": "5.7.2",
    "list.js": "1.5.0",
    "moment": "2.27.0",
    "next": "10.0.5",
    "next-compose-plugins": "2.2.0",
    "next-fonts": "1.4.0",
    "next-images": "1.3.1",
    "next-transpile-modules": "4.1.0",
    "node-sass": "4.14.1",
    "nouislider": "14.6.1",
    "path": "0.12.7",
    "prop-types": "15.7.2",
    "react": "16.13.1",
    "react-bootstrap-sweetalert": "5.2.0",
    "react-bootstrap-table-next": "4.0.3",
    "react-bootstrap-table2-paginator": "2.1.2",
    "react-bootstrap-table2-toolkit": "2.1.3",
    "react-chartjs-2": "2.10.0",
    "react-copy-to-clipboard": "5.0.2",
    "react-datetime": "2.16.3",
    "react-dom": "16.13.1",
    "react-google-maps": "9.4.5",
    "react-jvectormap": "0.0.16",
    "react-notification-alert": "0.0.12",
    "react-perfect-scrollbar": "1.5.8",
    "react-quill": "1.3.5",
    "react-select2-wrapper": "1.0.4-beta6",
    "react-tagsinput": "3.19.0",
    "react-to-print": "2.9.0",
    "reactstrap": "8.5.1",
    "webpack": "4.44.1"
  },
  "devDependencies": {
    "@types/googlemaps": "3.39.13",
    "@types/markerclustererplus": "2.1.33",
    "@types/react": "16.9.46"
  }
}

**Comment by brijzenda** [comment]
@EINazare 

Is there any component version mismatch here? 
"next": "10.0.5",
"react": "16.13.1",
"webpack": "4.44.1"
Should we try carets and tildes to expand compatibility range?
 
Also please check if devDependencies in the serverless package.json is not creating any compatibility issue. 
https://github.com/serverless/serverless/blob/master/package.json

Thanks

**Comment by einazare** [comment]
Hello again, guys,

I think the error comes from the fact that you have changed the `next` version of our product. Please, try with 
```
"next": "9.5.2",
```
We'll make an update to this product in 1-2 weeks. This week we're starting the update of our NextJS & Material products, and then we'll update this product as well.

Best,
Manu

**Comment by tejasadvait** [comment]
Hey Manu @EINazare,

Even with `next: 9.5.2` we're running into the issue. It is arising from additional setting in next.config.js due to our serverless deployment. When I insert `target: serverless` in next.config.js, I get the following error:
 
---------------------------------------------------------------------------------------
```
> next build

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled

info  - Creating an optimized production build  
warn  - Compiled with warnings

./node_modules/next/dist/next-server/server/load-components.js
Critical dependency: the request of a dependency is an expression

./node_modules/next/dist/next-server/server/load-components.js
Critical dependency: the request of a dependency is an expression

./node_modules/next/dist/next-server/server/require.js
Critical dependency: the request of a dependency is an expression

./node_modules/next/dist/next-server/server/require.js
Critical dependency: the request of a dependency is an expression

./node_modules/next/dist/next-server/server/require.js
Critical dependency: the request of a dependency is an expression

Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`. This does not opt-out pages with `getStaticProps`
Read more: https://err.sh/next.js/opt-out-auto-static-optimization


> Build error occurred
TypeError: Cannot read property 'style' of undefined
    at Object.p4r7 (/Users/trex/Git/Zenda/AdminPortal/admin_portal_app/.next/serverless/pages/admin/elements.js:23859:52)
    at __webpack_require__ (/Users/trex/Git/Zenda/AdminPortal/admin_portal_app/.next/serverless/pages/admin/elements.js:23:31)
    at Object.nikJ (/Users/trex/Git/Zenda/AdminPortal/admin_portal_app/.next/serverless/pages/admin/elements.js:23002:25)
    at __webpack_require__ (/Users/trex/Git/Zenda/AdminPortal/admin_portal_app/.next/serverless/pages/admin/elements.js:23:31)
    at Object.cuOD (/Users/trex/Git/Zenda/AdminPortal/admin_portal_app/.next/serverless/pages/admin/elements.js:17218:18)
    at __webpack_require__ (/Users/trex/Git/Zenda/AdminPortal/admin_portal_app/.next/serverless/pages/admin/elements.js:23:31)
    at Object.RG8o (/Users/trex/Git/Zenda/AdminPortal/admin_portal_app/.next/serverless/pages/admin/elements.js:10902:81)
    at __webpack_require__ (/Users/trex/Git/Zenda/AdminPortal/admin_portal_app/.next/serverless/pages/admin/elements.js:23:31)
    at Object.i6E2 (/Users/trex/Git/Zenda/AdminPortal/admin_portal_app/.next/serverless/pages/admin/elements.js:20206:87)
    at __webpack_require__ (/Users/trex/Git/Zenda/AdminPortal/admin_portal_app/.next/serverless/pages/admin/elements.js:23:31) {
  type: 'TypeError'
}
info  - Collecting page data .npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nextjs-argon-dashboard-pro@1.0.0 build: `next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nextjs-argon-dashboard-pro@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/trex/.npm/_logs/2021-01-26T21_59_11_643Z-debug.log
```
---------------------------------------------------------------------------------------

On the other hand, `target: serverless` works with the free version of the Argon dashboard. Due to several advantages of the serverless architecture, it is critical that we use the build target as serverless. Can you provide any assistance with making the pro version of Argon dashboard compatible with the serverless build target? Here is my next.config.js:

```
const withPlugins = require("next-compose-plugins");
const withImages = require("next-images");
const withSass = require("@zeit/next-sass");
const withCSS = require("@zeit/next-css");
const withFonts = require("next-fonts");
const webpack = require("webpack");
const path = require("path");
// for transpiling all ESM @fullcalendar/* packages
// also, for piping fullcalendar thru babel (to learn why, see babel.config.js)
const withTM = require("next-transpile-modules")(["@fullcalendar"]);

module.exports = withFonts(
  withCSS(
    withImages(
      withSass(
        withTM({
          target: 'serverless',
          webpack(config, options) {
            config.module.rules.push({
              test: /\.(eot|ttf|woff|woff2)$/,
              use: {
                loader: "url-loader",
              },
            });
            config.resolve.modules.push(path.resolve("./"));
            return config;
          },
        })
      )
    )
  )
);

```
Best,
Tejas

**Comment by einazare** [comment]
Hello again, @tejasadvait ,

Unfortunately, we do not have experience in working with `target: 'serverless',`.
I think the free version works since the FREE version does not make use of all the plugins of the PRO one.

I'll try to figure out a solution, but I've already tried for the last 2 days. I honestly do not know what to try more.
Any advice is apreciated.

Best,
Manu

**Comment by tejasadvait** [comment]
Hey Manu @EINazare,

Thank you for your reply. We have a working solution for `target: 'serverless'` for the pro version. We'll share the solution with you if you issue us a refund :) :smile:

Best,
Tejas

**Comment by einazare** [comment]
Hello again, @tejasadvait ,

No need. We've just solved it as well, and we'll release the fix in our new update, which is set for next week, I hope on Tuesday or Wednesday.
Thanks anyways.

Best,
Manu

**Comment by tsauzeau** [comment]
Hey @EINazare, glad to hear you will release an update of the product!
I just had the same issue as everyone, but after fixing it I got this error:

`Unhandled Runtime Error
TypeError: Dropzone is not a constructor`

On the pages/admin/components.js

 Will the update fix that or not? (and when the update will be released ?)
  
  Thanks!
  Thomas,

**Comment by einazare** [comment]
Hello guys, @tsauzeau 

Tomorrow I'll release the new update. It seems that my solution, from my first comment, does not work anymore 😢 . But we've solved both the `serverless` and `npm run build` command issues.

So, the solution for the Dropzone issue was to use `async` function on `React.useEffect` (`componentDidMount`), and then, inside the `async` function to use the dynamic import with await: https://nextjs.org/docs/advanced-features/dynamic-import.
Here is their example code:
```
import { useState } from 'react'

const names = ['Tim', 'Joe', 'Bel', 'Max', 'Lee']

export default function Page() {
  const [results, setResults] = useState()

  return (
    <div>
      <input
        type="text"
        placeholder="Search"
        onChange={async (e) => {
          const { value } = e.currentTarget
          // Dynamically load fuse.js
          const Fuse = (await import('fuse.js')).default
          const fuse = new Fuse(names)

          setResults(fuse.search(value))
        }}
      />
      <pre>Results: {JSON.stringify(results, null, 2)}</pre>
    </div>
  )
}
```

We've also had to use this solution for sortable tables (i.e. `list.js`), and also `React-Quill`. We actually changed the usage of ReactQuill to the simple version of `QuillJS`, since using the latter we can control the import of the Quill: https://quilljs.com/
You can check inside `pages/admin/sortable.js` and `pages/admin/components.js` to see the solution, after we make the new release tomorrow (04 Feb 2021).

Best,
Manu

**Comment by tsauzeau** [comment]
Hey @EINazare,

Thanks! I will wait tomorrow for the update :)

Btw the project is really great and easy to use, thanks for that!
I'm able to produce good results rapidly without being a nextjs or react master (I'm really far from a master actually).

Thanks,
Thomas,

**Comment by haardparmar** [comment]
Hi 
I am getting some errors while building 

info  - Checking validity of types  

Failed to compile.

./pages/components/appbar/appbar.js
17:17  Warning: Do not use <img>. Use Image from 'next/image' instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
17:17  Warning: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a11y/alt-text

./pages/components/minimalComponents/windowSize.js
17:57  Error: React Hook "useState" is called conditionally. React Hooks must be called in the exact same order in every component render. Did you accidentally call a React Hook after an early return?  react-hooks/rules-of-hooks
18:9  Error: React Hook "useEffect" is called conditionally. React Hooks must be called in the exact same order in every component render. Did you accidentally call a React Hook after an early return?  react-hooks/rules-of-hooks

./pages/index.js
8:7  Error: External synchronous scripts are forbidden. See: https://nextjs.org/docs/messages/no-sync-scripts  @next/next/no-sync-scripts

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules

![image](https://user-images.githubusercontent.com/71481567/155883595-4d1db63f-c1ff-4cdc-a83e-146598c15a25.png)

Please help me
